[package]
name = "library"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.117"
serde_json = "1.0.59"
serde_derive = "1"
clap = "2.33.3"
regex = "1"
reqwest = "0.9.18"